/**
 * Achievement System Configuration
 * Defines all available achievements/badges for the learning game
 */

const ACHIEVEMENTS = [
  {
    id: 0,
    name: 'First Steps',
    description: 'Complete your first exercise',
    icon: '🎯',
    points: 50,
    criteria: { exercises_completed: 1 },
  },
  {
    id: 1,
    name: 'Beginner',
    description: 'Complete Level 1-10',
    icon: '🌟',
    points: 100,
    criteria: { levels_completed: 10 },
  },
  {
    id: 2,
    name: 'Intermediate',
    description: 'Complete Level 11-20',
    icon: '⭐',
    points: 200,
    criteria: { levels_completed: 20 },
  },
  {
    id: 3,
    name: 'Advanced',
    description: 'Complete Level 21-30',
    icon: '🔥',
    points: 300,
    criteria: { levels_completed: 30 },
  },
  {
    id: 4,
    name: 'Professional',
    description: 'Complete Level 31-40',
    icon: '💎',
    points: 400,
    criteria: { levels_completed: 40 },
  },
  {
    id: 5,
    name: 'Expert',
    description: 'Complete all 50 levels',
    icon: '👑',
    points: 500,
    criteria: { levels_completed: 50 },
  },
  {
    id: 6,
    name: 'Speed Demon',
    description: 'Complete 10 exercises in under 5 minutes each',
    icon: '⚡',
    points: 150,
    criteria: { fast_completions: 10 },
  },
  {
    id: 7,
    name: 'No Hints Needed',
    description: 'Complete 20 exercises without using hints',
    icon: '🧠',
    points: 250,
    criteria: { no_hint_completions: 20 },
  },
  {
    id: 8,
    name: 'Persistent',
    description: 'Attempt the same exercise 10 times before succeeding',
    icon: '💪',
    points: 100,
    criteria: { max_attempts: 10 },
  },
  {
    id: 9,
    name: 'Leaderboard Top 10',
    description: 'Reach top 10 on the leaderboard',
    icon: '🏆',
    points: 300,
    criteria: { leaderboard_rank: 10 },
  },
  {
    id: 10,
    name: 'First Level Complete',
    description: 'Complete your first level entirely',
    icon: '🎁',
    points: 75,
    criteria: { level_completed: 1 },
  },
  {
    id: 11,
    name: 'Perfect Score',
    description: 'Complete a level with 100% accuracy on first try',
    icon: '✨',
    points: 200,
    criteria: { perfect_level: true },
  },
  {
    id: 12,
    name: 'Hint Master',
    description: 'Use 50 hints throughout your journey',
    icon: '🔓',
    points: 50,
    criteria: { hints_used: 50 },
  },
  {
    id: 13,
    name: 'Solo Master',
    description: 'Complete 50 exercises without using any hints',
    icon: '🎪',
    points: 350,
    criteria: { no_hint_completions: 50 },
  },
  {
    id: 14,
    name: 'Speed Runner',
    description: 'Complete 5 exercises in under 2 minutes each',
    icon: '🚀',
    points: 120,
    criteria: { very_fast_completions: 5 },
  },
  {
    id: 15,
    name: 'Breakthrough',
    description: 'Complete 5 exercises in a row without any mistakes',
    icon: '💡',
    points: 180,
    criteria: { perfect_streak: 5 },
  },
  {
    id: 16,
    name: 'Comeback Kid',
    description: 'Fail an exercise 5 times then finally complete it',
    icon: '📈',
    points: 90,
    criteria: { comeback_completion: true },
  },
  {
    id: 17,
    name: 'Dedicated Learner',
    description: 'Spend 10+ hours in the learning game',
    icon: '⏱️',
    points: 200,
    criteria: { hours_spent: 10 },
  },
  {
    id: 18,
    name: '7-Day Streak',
    description: 'Complete exercises for 7 consecutive days',
    icon: '🔥',
    points: 150,
    criteria: { consecutive_days: 7 },
  },
  {
    id: 19,
    name: 'Completionist',
    description: 'Earn all available achievements',
    icon: '🌈',
    points: 1000,
    criteria: { all_achievements: true },
  },
];

module.exports = { ACHIEVEMENTS };
